# Generated by Django 4.2.1 on 2023-07-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprice",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="promotional_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
