# Generated by Django 4.2.1 on 2023-07-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_productprice_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprice",
            name="product_id",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
    ]
