# Generated by Django 4.2.1 on 2023-07-14 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=64)),
                ("url", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Crawler",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(default=datetime.datetime.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("categories", models.IntegerField(default=0)),
                ("products", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                (
                    "site_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="crawler.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crawler",
            },
        ),
    ]
