# Generated by Django 4.2.1 on 2023-07-16 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crawler", "0005_alter_crawler_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "attribute",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sku", models.CharField(max_length=512)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(max_length=32)),
                ("uri", models.CharField(max_length=255)),
                ("crawler_date", models.CharField(max_length=255)),
                ("metadata", models.JSONField(max_length=1024)),
                (
                    "site_id",
                    models.ForeignKey(
                        db_column="category",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.site",
                    ),
                ),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        db_column="category",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
            options={
                "db_table": "sub_categorys",
            },
        ),
        migrations.CreateModel(
            name="ProductSizes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("size", models.CharField(max_length=64)),
                ("stock", models.IntegerField(blank=True, null=True)),
                ("crawled_at", models.DateField()),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "products_sizes",
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "promotional_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("crawled_at", models.DateField(blank=True, null=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "products_price",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.FloatField(blank=True)),
                (
                    "attribute_id",
                    models.ForeignKey(
                        db_column="attribute",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.attribute",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "products_attributes",
            },
        ),
    ]
