# Generated by Django 4.2.1 on 2023-07-16 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0004_alter_crawler_site_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crawler",
            options={"verbose_name": "Crawler", "verbose_name_plural": "Crawlers"},
        ),
    ]
